- hosts: all
  sudo: yes
  remote_user: vagrant   
  tasks:
  - name: Actualizar sistema 
    apt: update_cache=yes     	
  - name: Install git 
    apt: pkg=git state=present 
  - name: Clonar
    git:  repo=https://github.com/mati3/Gestion-Medicamentos-IV.git dest=Gestion-Medicamentos-IV/ clone=yes force=yes  
  - name: Build-essential
    apt: pkg=build-essential state=present     
  - name: Instala Ruby
    apt: pkg=ruby state=present
  - gem:
        name=sinatra
        state=latest
  - gem:
        name=bundle
        state=latest
